/*
  Simple Ascii Renderer
  Copyright (C) 2016 Thomas Guyot <thomasguyot@outlook.com>

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/
#ifndef __SAR__
#define __SAR__

#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
#include <stdio.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

//------------------------------------------------------------------------------
// Globals
//------------------------------------------------------------------------------

extern int SAR_TILE_WIDTH;
extern int SAR_TILE_HEIGHT;

//------------------------------------------------------------------------------
// Enumerations
//------------------------------------------------------------------------------

// ASCII CP437 characters (255)
// Adapted from https://gist.github.com/inmatarian/ef2bce24301f53349c7e (Thanks a lot!)
typedef enum
{
	CHAR_NULL = 0,
	CHAR_EMPTY_SMILEY = 1,
	CHAR_SMILEY = 2,
	CHAR_HEART = 3,
	CHAR_DIAMOND = 4,
	CHAR_CLUB = 5,
	CHAR_SPADE = 6,
	CHAR_DOT = 7,
	CHAR_INVERSE_DOT = 8,
	CHAR_CIRCLE = 9,
	CHAR_INVERSE_CIRCLE = 10,
	CHAR_MALE_MARS = 11,
	CHAR_FEMALE_VENUS = 12,
	CHAR_SINGLE_NOTE = 13,
	CHAR_DOUBLE_NOTE = 14,
	CHAR_STAR = 15,
	CHAR_RIGHT_FAT_ARROW = 16,
	CHAR_LEFT_FAT_ARROW = 17,
	CHAR_DOUBLE_VERTICAL_ARROW = 18,
	CHAR_DOUBLE_EXCLAMATION_MARK = 19,
	CHAR_PARAGRAPH = 20,
	CHAR_SECTION = 21,
	CHAR_BAR = 22,
	CHAR_UNDERSCORED_DOUBLE_VERTICAL_ARROW = 23,
	CHAR_UP_ARROW = 24,
	CHAR_DOWN_ARROW = 25,
	CHAR_RIGHT_ARROW = 26,
	CHAR_LEFT_ARROW = 27,
	CHAR_INVERTED_NOT_SIGN = 28,
	CHAR_DOUBLE_HORIZONTAL_ARROW = 29,
	CHAR_UP_FAT_ARROW = 30,
	CHAR_DOWN_FAT_ARROW = 31,
	CHAR_SPACE = 32,
	CHAR_EXCLAMATION_MARK = 33,
	CHAR_QUOTES = 34,
	CHAR_HASH = 35,
	CHAR_DOLLAR = 36,
	CHAR_PERCENT = 37,
	CHAR_AMPERSAND = 38,
	CHAR_APOSTROPHE = 39,
	CHAR_OPEN_BRACKET = 40,
	CHAR_CLOSE_BRACKET = 41,
	CHAR_ASTERISK = 42,
	CHAR_PLUS = 43,
	CHAR_COMMA = 44,
	CHAR_DASH = 45,
	CHAR_FULL_STOP = 46,
	CHAR_SLASH = 47,
	CHAR_ZERO = 48,
	CHAR_ONE = 49,
	CHAR_TWO = 50,
	CHAR_THREE = 51,
	CHAR_FOUR = 52,
	CHAR_FIVE = 53,
	CHAR_SIX = 54,
	CHAR_SEVEN = 55,
	CHAR_EIGHT = 56,
	CHAR_NINE = 57,
	CHAR_COLON = 58,
	CHAR_SEMI_COLON = 59,
	CHAR_LESS_THAN = 60,
	CHAR_EQUALS = 61,
	CHAR_GREATER_THAN = 62,
	CHAR_QUESTION_MARK = 63,
	CHAR_AT = 64,
	CHAR_UPPERCASE_A = 65,
	CHAR_UPPERCASE_B = 66,
	CHAR_UPPERCASE_C = 67,
	CHAR_UPPERCASE_D = 68,
	CHAR_UPPERCASE_E = 69,
	CHAR_UPPERCASE_F = 70,
	CHAR_UPPERCASE_G = 71,
	CHAR_UPPERCASE_H = 72,
	CHAR_UPPERCASE_I = 73,
	CHAR_UPPERCASE_J = 74,
	CHAR_UPPERCASE_K = 75,
	CHAR_UPPERCASE_L = 76,
	CHAR_UPPERCASE_M = 77,
	CHAR_UPPERCASE_N = 78,
	CHAR_UPPERCASE_O = 79,
	CHAR_UPPERCASE_P = 80,
	CHAR_UPPERCASE_Q = 81,
	CHAR_UPPERCASE_R = 82,
	CHAR_UPPERCASE_S = 83,
	CHAR_UPPERCASE_T = 84,
	CHAR_UPPERCASE_U = 85,
	CHAR_UPPERCASE_V = 86,
	CHAR_UPPERCASE_W = 87,
	CHAR_UPPERCASE_X = 88,
	CHAR_UPPERCASE_Y = 89,
	CHAR_UPPERCASE_Z = 90,
	CHAR_OPEN_SQUARE_BRACKET = 91,
	CHAR_BACKSLASH = 92,
	CHAR_CLOSE_SQUARE_BRACKET = 93,
	CHAR_CARET = 94,
	CHAR_UNDERSCORE = 95,
	CHAR_GRAVE_ACCENT = 96,
	CHAR_LOWERCASE_A = 97,
	CHAR_LOWERCASE_B = 98,
	CHAR_LOWERCASE_C = 99,
	CHAR_LOWERCASE_D = 100,
	CHAR_LOWERCASE_E = 101,
	CHAR_LOWERCASE_F = 102,
	CHAR_LOWERCASE_G = 103,
	CHAR_LOWERCASE_H = 104,
	CHAR_LOWERCASE_I = 105,
	CHAR_LOWERCASE_J = 106,
	CHAR_LOWERCASE_K = 107,
	CHAR_LOWERCASE_L = 108,
	CHAR_LOWERCASE_M = 109,
	CHAR_LOWERCASE_N = 110,
	CHAR_LOWERCASE_O = 111,
	CHAR_LOWERCASE_P = 112,
	CHAR_LOWERCASE_Q = 113,
	CHAR_LOWERCASE_R = 114,
	CHAR_LOWERCASE_S = 115,
	CHAR_LOWERCASE_T = 116,
	CHAR_LOWERCASE_U = 117,
	CHAR_LOWERCASE_V = 118,
	CHAR_LOWERCASE_W = 119,
	CHAR_LOWERCASE_X = 120,
	CHAR_LOWERCASE_Y = 121,
	CHAR_LOWERCASE_Z = 122,
	CHAR_OPEN_BRACE = 123,
	CHAR_PIPE = 124,
	CHAR_CLOSE_BRACE = 125,
	CHAR_TILDE = 126,
	CHAR_DELETE = 127,
	CHAR_LATIN_CAPITAL_LETTER_C_WITH_CEDILLA = 128,
	CHAR_LATIN_SMALL_LETTER_U_WITH_DIAERESIS = 129,
	CHAR_LATIN_SMALL_LETTER_E_WITH_ACUTE = 130,
	CHAR_LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX = 131,
	CHAR_LATIN_SMALL_LETTER_A_WITH_DIAERESIS = 132,
	CHAR_LATIN_SMALL_LETTER_A_WITH_GRAVE = 133,
	CHAR_LATIN_SMALL_LETTER_A_WITH_RING_ABOVE = 134,
	CHAR_LATIN_SMALL_LETTER_C_WITH_CEDILLA = 135,
	CHAR_LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX = 136,
	CHAR_LATIN_SMALL_LETTER_E_WITH_DIAERESIS = 137,
	CHAR_LATIN_SMALL_LETTER_E_WITH_GRAVE = 138,
	CHAR_LATIN_SMALL_LETTER_I_WITH_DIAERESIS = 139,
	CHAR_LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX = 140,
	CHAR_LATIN_SMALL_LETTER_I_WITH_GRAVE = 141,
	CHAR_LATIN_CAPITAL_LETTER_A_WITH_DIAERESIS = 142,
	CHAR_LATIN_CAPITAL_LETTER_A_WITH_RING_ABOVE = 143,
	CHAR_LATIN_CAPITAL_LETTER_E_WITH_ACUTE = 144,
	CHAR_LATIN_SMALL_LIGATURE_AE = 145,
	CHAR_LATIN_CAPITAL_LIGATURE_AE = 146,
	CHAR_LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX = 147,
	CHAR_LATIN_SMALL_LETTER_O_WITH_DIAERESIS = 148,
	CHAR_LATIN_SMALL_LETTER_O_WITH_GRAVE = 149,
	CHAR_LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX = 150,
	CHAR_LATIN_SMALL_LETTER_U_WITH_GRAVE = 151,
	CHAR_LATIN_SMALL_LETTER_Y_WITH_DIAERESIS = 152,
	CHAR_LATIN_CAPITAL_LETTER_O_WITH_DIAERESIS = 153,
	CHAR_LATIN_CAPITAL_LETTER_U_WITH_DIAERESIS = 154,
	CHAR_CENT_SIGN = 155,
	CHAR_POUND_SIGN = 156,
	CHAR_YEN_SIGN = 157,
	CHAR_PESETA_SIGN = 158,
	CHAR_LATIN_SMALL_LETTER_F_WITH_HOOK = 159,
	CHAR_LATIN_SMALL_LETTER_A_WITH_ACUTE = 160,
	CHAR_LATIN_SMALL_LETTER_I_WITH_ACUTE = 161,
	CHAR_LATIN_SMALL_LETTER_O_WITH_ACUTE = 162,
	CHAR_LATIN_SMALL_LETTER_U_WITH_ACUTE = 163,
	CHAR_LATIN_SMALL_LETTER_N_WITH_TILDE = 164,
	CHAR_LATIN_CAPITAL_LETTER_N_WITH_TILDE = 165,
	CHAR_FEMININE_ORDINAL_INDICATOR = 166,
	CHAR_MASCULINE_ORDINAL_INDICATOR = 167,
	CHAR_INVERTED_QUESTION_MARK = 168,
	CHAR_REVERSED_NOT_SIGN = 169,
	CHAR_NOT_SIGN = 170,
	CHAR_VULGAR_FRACTION_ONE_HALF = 171,
	CHAR_VULGAR_FRACTION_ONE_QUARTER = 172,
	CHAR_INVERTED_EXCLAMATION_MARK = 173,
	CHAR_LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK = 174,
	CHAR_RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK = 175,
	CHAR_LIGHT_SHADE = 176,
	CHAR_MEDIUM_SHADE = 177,
	CHAR_DARK_SHADE = 178,
	CHAR_BOX_DRAWINGS_LIGHT_VERTICAL = 179,
	CHAR_BOX_DRAWINGS_LIGHT_VERTICAL_AND_LEFT = 180,
	CHAR_BOX_DRAWINGS_VERTICAL_SINGLE_AND_LEFT_DOUBLE = 181,
	CHAR_BOX_DRAWINGS_VERTICAL_DOUBLE_AND_LEFT_SINGLE = 182,
	CHAR_BOX_DRAWINGS_DOWN_DOUBLE_AND_LEFT_SINGLE = 183,
	CHAR_BOX_DRAWINGS_DOWN_SINGLE_AND_LEFT_DOUBLE = 184,
	CHAR_BOX_DRAWINGS_DOUBLE_VERTICAL_AND_LEFT = 185,
	CHAR_BOX_DRAWINGS_DOUBLE_VERTICAL = 186,
	CHAR_BOX_DRAWINGS_DOUBLE_DOWN_AND_LEFT = 187,
	CHAR_BOX_DRAWINGS_DOUBLE_UP_AND_LEFT = 188,
	CHAR_BOX_DRAWINGS_UP_DOUBLE_AND_LEFT_SINGLE = 189,
	CHAR_BOX_DRAWINGS_UP_SINGLE_AND_LEFT_DOUBLE = 190,
	CHAR_BOX_DRAWINGS_LIGHT_DOWN_AND_LEFT = 191,
	CHAR_BOX_DRAWINGS_LIGHT_UP_AND_RIGHT = 192,
	CHAR_BOX_DRAWINGS_LIGHT_UP_AND_HORIZONTAL = 193,
	CHAR_BOX_DRAWINGS_LIGHT_DOWN_AND_HORIZONTAL = 194,
	CHAR_BOX_DRAWINGS_LIGHT_VERTICAL_AND_RIGHT = 195,
	CHAR_BOX_DRAWINGS_LIGHT_HORIZONTAL = 196,
	CHAR_BOX_DRAWINGS_LIGHT_VERTICAL_AND_HORIZONTAL = 197,
	CHAR_BOX_DRAWINGS_VERTICAL_SINGLE_AND_RIGHT_DOUBLE = 198,
	CHAR_BOX_DRAWINGS_VERTICAL_DOUBLE_AND_RIGHT_SINGLE = 199,
	CHAR_BOX_DRAWINGS_DOUBLE_UP_AND_RIGHT = 200,
	CHAR_BOX_DRAWINGS_DOUBLE_DOWN_AND_RIGHT = 201,
	CHAR_BOX_DRAWINGS_DOUBLE_UP_AND_HORIZONTAL = 202,
	CHAR_BOX_DRAWINGS_DOUBLE_DOWN_AND_HORIZONTAL = 203,
	CHAR_BOX_DRAWINGS_DOUBLE_VERTICAL_AND_RIGHT = 204,
	CHAR_BOX_DRAWINGS_DOUBLE_HORIZONTAL = 205,
	CHAR_BOX_DRAWINGS_DOUBLE_VERTICAL_AND_HORIZONTAL = 206,
	CHAR_BOX_DRAWINGS_UP_SINGLE_AND_HORIZONTAL_DOUBLE = 207,
	CHAR_BOX_DRAWINGS_UP_DOUBLE_AND_HORIZONTAL_SINGLE = 208,
	CHAR_BOX_DRAWINGS_DOWN_SINGLE_AND_HORIZONTAL_DOUBLE = 209,
	CHAR_BOX_DRAWINGS_DOWN_DOUBLE_AND_HORIZONTAL_SINGLE = 210,
	CHAR_BOX_DRAWINGS_UP_DOUBLE_AND_RIGHT_SINGLE = 211,
	CHAR_BOX_DRAWINGS_UP_SINGLE_AND_RIGHT_DOUBLE = 212,
	CHAR_BOX_DRAWINGS_DOWN_SINGLE_AND_RIGHT_DOUBLE = 213,
	CHAR_BOX_DRAWINGS_DOWN_DOUBLE_AND_RIGHT_SINGLE = 214,
	CHAR_BOX_DRAWINGS_VERTICAL_DOUBLE_AND_HORIZONTAL_SINGLE = 215,
	CHAR_BOX_DRAWINGS_VERTICAL_SINGLE_AND_HORIZONTAL_DOUBLE = 216,
	CHAR_BOX_DRAWINGS_LIGHT_UP_AND_LEFT = 217,
	CHAR_BOX_DRAWINGS_LIGHT_DOWN_AND_RIGHT = 218,
	CHAR_FULL_BLOCK = 219,
	CHAR_LOWER_HALF_BLOCK = 220,
	CHAR_LEFT_HALF_BLOCK = 221,
	CHAR_RIGHT_HALF_BLOCK = 222,
	CHAR_UPPER_HALF_BLOCK = 223,
	CHAR_GREEK_SMALL_LETTER_ALPHA = 224,
	CHAR_LATIN_SMALL_LETTER_SHARP_S = 225,
	CHAR_GREEK_CAPITAL_LETTER_GAMMA = 226,
	CHAR_GREEK_SMALL_LETTER_PI = 227,
	CHAR_GREEK_CAPITAL_LETTER_SIGMA = 228,
	CHAR_GREEK_SMALL_LETTER_SIGMA = 229,
	CHAR_MICRO_SIGN = 230,
	CHAR_GREEK_SMALL_LETTER_TAU = 231,
	CHAR_GREEK_CAPITAL_LETTER_PHI = 232,
	CHAR_GREEK_CAPITAL_LETTER_THETA = 233,
	CHAR_GREEK_CAPITAL_LETTER_OMEGA = 234,
	CHAR_GREEK_SMALL_LETTER_DELTA = 235,
	CHAR_INFINITY = 236,
	CHAR_GREEK_SMALL_LETTER_PHI = 237,
	CHAR_GREEK_SMALL_LETTER_EPSILON = 238,
	CHAR_INTERSECTION = 239,
	CHAR_IDENTICAL_TO = 240,
	CHAR_PLUS_MINUS_SIGN = 241,
	CHAR_GREATER_THAN_OR_EQUAL_TO = 242,
	CHAR_LESS_THAN_OR_EQUAL_TO = 243,
	CHAR_TOP_HALF_INTEGRAL = 244,
	CHAR_BOTTOM_HALF_INTEGRAL = 245,
	CHAR_DIVISION_SIGN = 246,
	CHAR_ALMOST_EQUAL_TO = 247,
	CHAR_DEGREE_SIGN = 248,
	CHAR_BULLET_OPERATOR = 249,
	CHAR_MIDDLE_DOT = 250,
	CHAR_SQUARE_ROOT = 251,
	CHAR_SUPERSCRIPT_LATIN_SMALL_LETTER_N = 252,
	CHAR_SUPERSCRIPT_TWO = 253,
	CHAR_BLACK_SQUARE = 254,
	CHAR_NO_BREAK_SPACE = 255
} ascii_characters;

//------------------------------------------------------------------------------
// Types
//------------------------------------------------------------------------------

typedef SDL_Event sar_event;
typedef SDL_Color sar_color;

//------------------------------------------------------------------------------
// Initialization and shutdown
//------------------------------------------------------------------------------

bool sar_init(const char * caption, int w, int h, bool resizable);
void sar_close(void);

//------------------------------------------------------------------------------
// Image/file loading
//------------------------------------------------------------------------------

bool sar_load_texture(const char * path);

//------------------------------------------------------------------------------
// Events handling
//------------------------------------------------------------------------------

int sar_get_events(sar_event * event);

//------------------------------------------------------------------------------
// Rendering
//------------------------------------------------------------------------------

void sar_begin_rendering(sar_color clear_color);
void sar_end_rendering(void);
void sar_render_tile(long c, int x, int y, sar_color bg_color, sar_color tile_color);
void sar_render_str(const char * str, int x, int y, sar_color bg_color, sar_color tile_color);

#ifdef __cplusplus
}
#endif

#endif // __SAR__
