all:
	gcc-5 tests.c -o tests.out -I/usr/local/include/ -L/Users/thomasguyot/libascii -lsar

cpp:
	g++-5 tests.cpp -o testscpp.out -I/usr/local/include/ -L/Users/thomasguyot/libascii -lsar

clean:
	rm *.out